### ISSUE TITLE
GIF Support is gone after last update of TweetDeck

### ISSUE THREAD

**Issue by XSilverlink** [MehediH/Tweeten#141]
It is just as the title says. After the last update GIF support is gone.
Better Tweetdeck had this issue too but it is fixed.

Can you please look into it. I prefer Tweeten over Better Tweetdeck as this is a standalone app.

**Comment by nykoo** [comment]
emoticons icon also disapear in "new tweet" :/

**Comment by XSilverlink** [comment]
Is this project abandoned?

**Comment by nykoo** [comment]
<blockquote class="twitter-tweet" data-lang="fr"><p lang="en" dir="ltr">I got an exam in a few hours but because you guys can&#39;t stop complaining about the emoji/gif feature going missing, I decided to fix it instead of revising. New update coming tonight hopefully. <a href="https://t.co/52ngSusFoJ">pic.twitter.com/52ngSusFoJ</a></p>&mdash; Tweeten (@TweetenApp) <a href="https://twitter.com/TweetenApp/status/1107961348422541313?ref_src=twsrc%5Etfw">19 mars 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by XSilverlink** [comment]
Ah thanks @nykoo! Glad he is updating it. Don't want to see this program abandoned.
