### ISSUE TITLE
canot load

### ISSUE THREAD

**Issue by aniontsui** [MehediH/Tweeten#148]

**Comment by tylerregas** [comment]
If you are having the same problem, then I discovered this today, as well. I installed it to my laptop which is set to install all apps to my D: drive, but I was getting rename errors. Tweeten must be installed to the System drive, typically C:, in order to work. Try going to: 

1. Start > Settings > Apps
2. Search for Tweeten and select it
3. Click Move
4. Select your System drive
5. Click OK

Once it's done with it's business (it doesn't move quickly, so give it time), it should load. 

Mehedi needs to add the hooks to the app that tell Windows 10 to enforce installation only to the System drive for modern apps, which will solve that problem. Most modern apps don't require this, but some do. 

Hope this helps!
