### ISSUE TITLE
Unable to add multiple accounts

### ISSUE THREAD

**Issue by arpieb** [MehediH/Tweeten#151]
Running 4.7.0 on Windows 10 x64, and I see no option to add a new account, just shared accounts (which I don't want - I want to actually toggle between accounts like I do with Twitterific on my Mac).

It seems this request has been made several times and keeps getting closed as "it works" - yet it doesn't.

Is there a reason it's not being addressed?

**Comment by BradyThe** [comment]
> Is there a reason it's not being addressed?

I believe that there are a couple of interpretations floating around what the option of 'multiple accounts' includes.

I personally prefer being able to toggle between accounts as well, instead of being able to add different account columns through shared accounts, simply because of verticality reasons using Tweeten on only one screen.

To my knowledge there doesn't seem to be an integrated option to switch easily between accounts, so I pieced together my own version (which might not be as elegant as it could be, but that's all I was able to cobble together).

It's a simple batch file that will shuffle around the cookie file in which the login data is stored:
https://pastebin.com/0xEX028Q

This solution will require you to log into ACCOUNT1, rename the file 'Cookies' (located at %appdata%\Tweeten), into 'Cookies-ACCOUNT1', and log into ACCOUNT2 to generate the 'Cookies' file.

In my case the batch file is located directly in %appdata%\Tweeten because I have a keyboard with macro keys. Depending on where you want to store the batch file, if you want to use this method until the time Mehedi adds this option to Tweeten. ;-), you have to make some adjustments.

Cheers.
