### ISSUE TITLE
Search and write buttons overlapping

### ISSUE THREAD

**Issue by markscherz** [MehediH/Tweeten#159]
For several months now the search and write tweet buttons in my tweeten have been overlapping one another. 
<img width="42" alt="Screenshot 2019-11-25 at 15 42 08" src="https://user-images.githubusercontent.com/46906676/69549788-35c98180-0f9a-11ea-8a1a-0ef7517b482c.png">
This does not go away if I log out and log in, quit the app, restart the computer, update the app, or under any other conditions. Clicking it brings up the search bar. Clicking the empty square does nothing whatsoever. However, if I close the tweet composer, the two do separate and the upper button becomes a click-able pencil icon. Once clicked, the two overlap again and we are back to square one.

MacBook Pro 2016 running OSX Mojave 10.14.6

**Comment by daniels1989** [comment]
The same thing happens on my Windows 10 1909 machine.

A similar bug happens if you open the Accounts flyout, although then it's the search buttonthat goes down about 2 spaces.

![screenshot 2020-01-12](https://user-images.githubusercontent.com/559293/72224414-a47a9280-357a-11ea-8071-6a5b898050d8.png)
