### ISSUE TITLE
Add Account feature missing

### ISSUE THREAD

**Issue by megglatron** [MehediH/Tweeten#31]
Hi there, 

I stumbled across Tweeten because the same issue I'm writing to you about is also present on Tweetdeck: The 'Add Account' feature is no longer present in the application. 

In the 'Accounts' tab you can still see your accessible accounts, but I am unable to add any more. 

![screen shot 2017-09-28 at 3 56 12 pm](https://user-images.githubusercontent.com/18358634/30951331-b7e3e31a-a465-11e7-8e9c-3070e2803007.png)

OS: MacOS Sierra ver. 10.12.6

Please let me know if I can provide any further detail. 

Cheers, 
Meg

**Comment by king-of-the-internet** [comment]
Adding to this ticket because I was just about to file a new one with the same issue in question.

![tweeten bug](https://user-images.githubusercontent.com/16597313/31226753-b2bb29fa-a9ad-11e7-8914-325d1d711d38.png)

Running Win10 64-bit. Issue persists both in normal execution, administrator mode, compatibility mode, etc.

Regards.

**Comment by MehediH** [comment]
Hi guys, this has been fixed in the latest versions of Tweeten.

**Comment by AfonsoGomes** [comment]
I know this has been closed but I am not able to add a new account. It seems to be missing similar to the previous comments.

Version: 4.3.1
Windows 10 Fall Creators Update - both Microsoft Store and 64-bit downloaded version
