### ISSUE TITLE
Custom CSS overridden by app

### ISSUE THREAD

**Issue by venkatperi** [MehediH/Tweeten#51]
Css injected via `Settings | Advanced` is overridden by the app's css. Also it appears that custom css doesn't retain `!important`, making it impossible to change styles such as username:

The custom css from `Settings | Advanced`:
```
.js-app .js-column .stream-item .account-link .account-inline .fullname {
    font-weight: 300 !important;
    letter-spacing: inherit  !important;
}
```

Custom css (overridden by below) as seen in debug inspector:
```
.js-app .js-column .stream-item .account-link .account-inline .fullname {
    font-weight: 300;
    letter-spacing: inherit;
}
```

Injected above custom css:
```
.js-app .js-column .stream-item .account-link .account-inline .username {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
    font-weight: 600;
    color: rgb(86, 86, 86);
}
```

**Comment by MehediH** [comment]
Because of how Electron handles CSS injection and how Tweeten works with the default TweetDeck CSS, some of the custom CSS stuff won't work.

**Comment by chevas** [comment]
Exceedingly unfortunate. The default css for the tweetdeck titling of the columns highlights the kind of messages ("Home", "Notifications", etc.) while dimming the actual account name the column represents. I need to bring greater attention to the account name (size, color, opacity, etc.) in order to more easily scan the columns.
